import Head from "next/head";
import Hero from "../components/Hero.jsx";
// import about from "./about.jsx";
import Info from "../components/Info.jsx";

import Navbar from "../components/Navbar.jsx";
import Projects from "../components/Projects.jsx";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ajhel</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero heading="hi, im ajhel" message="" block="about me" />
      <Info />
      <Projects />
    </div>
  );
}
